name: Build busybox and git auto commit

on:
  workflow_dispatch:

env:
  BUSYBOX_URL: https://busybox.net/downloads/busybox-1.36.0.tar.bz2
  BUSYBOX_DIRNAME: busybox-1.36.0

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - name: Install build dependencies
        run: "\
          sudo apt-get update\n
          sudo apt-get install -y --no-install-recommends build-essential wget ca-certificates \
          file qemu-user-static \
          g++-aarch64-linux-gnu g++-arm-linux-gnueabi g++-arm-linux-gnueabihf g++-mips-linux-gnu g++-mipsel-linux-gnu \
          g++-mips64-linux-gnuabi64 g++-mips64el-linux-gnuabi64 g++-powerpc64le-linux-gnu g++-riscv64-linux-gnu\n
          mkdir busybox\n
        "
      - name: Get busybox
        run: |
          wget $BUSYBOX_URL
          tar jxvf ${BUSYBOX_URL##*/}
        working-directory: busybox
      - name: Build busybox for x86_64
        run: |
          mkdir build
          cd build
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-x86_64-linux-gnu"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-x86_64-linux-gnu"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for aarch64
        run: |
          mkdir build
          cd build
          export ARCH=aarch64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for arm-linux-gnueabi
        run: |
          mkdir build
          cd build
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for arm-linux-gnueabihf
        run: |
          mkdir build
          cd build
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabihf-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for mips-linux-gnu
        run: |
          mkdir build
          cd build
          export ARCH=mips
          export CROSS_COMPILE=mips-linux-gnu-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for mipsel-linux-gnu
        run: |
          mkdir build
          cd build
          export ARCH=mips
          export CROSS_COMPILE=mipsel-linux-gnu-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for mips64-linux-gnuabi64
        run: |
          mkdir build
          cd build
          export ARCH=mips64
          export CROSS_COMPILE=mips64-linux-gnuabi64-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for mips64el-linux-gnuabi64
        run: |
          mkdir build
          cd build
          export ARCH=mips64
          export CROSS_COMPILE=mips64el-linux-gnuabi64-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for powerpc64le-linux-gnu
        run: |
          mkdir build
          cd build
          export ARCH=powerpc
          export CROSS_COMPILE=powerpc64le-linux-gnu-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Build busybox for riscv64-linux-gnu
        run: |
          mkdir build
          cd build
          export ARCH=riscv
          export CROSS_COMPILE=riscv64-linux-gnu-
          make KBUILD_SRC="../$BUSYBOX_DIRNAME" -f "../$BUSYBOX_DIRNAME/Makefile" defconfig
          sed -e 's/.*\<CONFIG_STATIC\>.*/CONFIG_STATIC=y/' -i .config
          make -j$(($(nproc)+1))
          cp busybox "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          chmod +x "$GITHUB_WORKSPACE/main/busybox-${CROSS_COMPILE::-1}"
          cd ..
          rm -rf build
        working-directory: busybox
      - name: Update README.md
        run: |
          head -n2 README.md | tee README.md > /dev/null
          echo -e "busybox v${BUSYBOX_DIRNAME##busybox-} static binaries\n" >> README.md
          echo '```console' >> README.md
          /bin/bash -c 'PS4="$ "; set -x; file ./busybox-*' &>> README.md
          echo -e '```\n' >> README.md
          echo '# bundled commands' >> README.md
          echo '```console' >> README.md
          /bin/bash -c 'PS4="$ "; set -x; qemu-aarch64-static ./busybox-aarch64-linux-gnu' &>> README.md
          echo '```' >> README.md
        working-directory: main
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./main
